import { Router } from 'express';
import type { CreateAiReportResponse } from '@ccovert/shared';
import { requireVerifiedEmail } from '../middleware/auth';
import { asyncHandler, badRequest } from '../utils/errors';
import { sameOriginMiddleware } from '../utils/session';
import { createAiReportRequestSchema, idSchema } from '../utils/validation';
import { aiReportService } from '../services/ai';

export function createAiRouter(): Router {
  const router = Router();

  router.get('/status', requireVerifiedEmail, (_request, response) => {
    const status = aiReportService.aiStatus();
    response.json({
      ...status,
      fallback: 'deterministic-summary',
      note: status.configured
        ? 'Reports are generated by the configured provider and validated against the stored records.'
        : 'No AI provider is configured. Reports are deterministic summaries of stored numbers, never generated narrative.'
    });
  });

  router.get('/reports', requireVerifiedEmail, asyncHandler(async (request, response) => {
    response.json({ reports: await aiReportService.list(request.user!.id) });
  }));

  router.get('/reports/:id', requireVerifiedEmail, asyncHandler(async (request, response) => {
    response.json({ report: await aiReportService.get(idSchema.parse(request.params.id), request.user!.id) });
  }));

  router.post('/reports', requireVerifiedEmail, sameOriginMiddleware, asyncHandler(async (request, response) => {
    const input = createAiReportRequestSchema.parse(request.body);
    if (input.uploadIds.length > 0) throw badRequest('AI reports can only use this account’s prediction history. File evidence is not supported.');
    const report = await aiReportService.create({
      userId: request.user!.id,
      predictionIds: input.predictionIds,
      uploadIds: input.uploadIds,
      question: input.question
    });
    const result: CreateAiReportResponse = { report };
    response.status(201).json(result);
  }));

  return router;
}
